name: Run Unit Tests
on: 
    push:
        paths:
          - 'software/*'
          - '.github/workflows/test.yml' # Trigger on changes to the workflow file
    pull_request:
        paths:
          - 'software/*'
          - '.github/workflows/test.yml' # Trigger on changes to the workflow file


defaults:
  run:
    working-directory: software

jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        python-version: ["3.12"]  
  
    steps:  
      - name: Check out source code
        uses: actions/checkout@v3  
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Generate lockfile
        run: pdm lock --group :all ${{ matrix.dep-versions == 'minimal' && '--strategy direct_minimal_versions' || '' }}
      - name: Install dependencies
        run: pdm sync  
      - name: Run tests  
        run: pdm run test
        
